# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Episode.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EpisodeInfoForm(object):
    def setupUi(self, EpisodeInfoForm):
        EpisodeInfoForm.setObjectName("EpisodeInfoForm")
        EpisodeInfoForm.resize(572, 488)
        self.centralwidget = QtWidgets.QWidget(EpisodeInfoForm)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(40, 20, 471, 101))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.lblTitle.setFont(font)
        self.lblTitle.setScaledContents(False)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setWordWrap(True)
        self.lblTitle.setObjectName("lblTitle")
        self.lblPlot = QtWidgets.QLabel(self.centralwidget)
        self.lblPlot.setGeometry(QtCore.QRect(20, 290, 531, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPlot.setFont(font)
        self.lblPlot.setWordWrap(True)
        self.lblPlot.setObjectName("lblPlot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 210, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.lblRating = QtWidgets.QLabel(self.centralwidget)
        self.lblRating.setGeometry(QtCore.QRect(190, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblRating.setFont(font)
        self.lblRating.setText("")
        self.lblRating.setTextFormat(QtCore.Qt.AutoText)
        self.lblRating.setObjectName("lblRating")
        self.lblReleased = QtWidgets.QLabel(self.centralwidget)
        self.lblReleased.setGeometry(QtCore.QRect(190, 210, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblReleased.setFont(font)
        self.lblReleased.setText("")
        self.lblReleased.setTextFormat(QtCore.Qt.AutoText)
        self.lblReleased.setObjectName("lblReleased")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 160, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.lblRating_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblRating_2.setGeometry(QtCore.QRect(340, 210, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblRating_2.setFont(font)
        self.lblRating_2.setText("")
        self.lblRating_2.setTextFormat(QtCore.Qt.AutoText)
        self.lblRating_2.setObjectName("lblRating_2")
        EpisodeInfoForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EpisodeInfoForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        EpisodeInfoForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EpisodeInfoForm)
        self.statusbar.setObjectName("statusbar")
        EpisodeInfoForm.setStatusBar(self.statusbar)
        self.actionGo_Back = QtWidgets.QAction(EpisodeInfoForm)
        self.actionGo_Back.setObjectName("actionGo_Back")
        self.actionExit_Application = QtWidgets.QAction(EpisodeInfoForm)
        self.actionExit_Application.setObjectName("actionExit_Application")
        self.menuFile.addAction(self.actionGo_Back)
        self.menuFile.addAction(self.actionExit_Application)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(EpisodeInfoForm)
        QtCore.QMetaObject.connectSlotsByName(EpisodeInfoForm)

    def retranslateUi(self, EpisodeInfoForm):
        _translate = QtCore.QCoreApplication.translate
        EpisodeInfoForm.setWindowTitle(_translate("EpisodeInfoForm", "MainWindow"))
        self.lblTitle.setText(_translate("EpisodeInfoForm", "Title"))
        self.lblPlot.setText(_translate("EpisodeInfoForm", "TextLabel"))
        self.label.setText(_translate("EpisodeInfoForm", "IMDB Rating:"))
        self.label_2.setText(_translate("EpisodeInfoForm", "Released:"))
        self.label_3.setText(_translate("EpisodeInfoForm", "Actors:"))
        self.menuFile.setTitle(_translate("EpisodeInfoForm", "File"))
        self.actionGo_Back.setText(_translate("EpisodeInfoForm", "Go Back"))
        self.actionExit_Application.setText(_translate("EpisodeInfoForm", "Exit Application"))

