# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1039, 918)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 100, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtSearch = QtWidgets.QTextEdit(Dialog)
        self.txtSearch.setGeometry(QtCore.QRect(250, 110, 321, 21))
        self.txtSearch.setObjectName("txtSearch")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lblPoster = QtWidgets.QLabel(Dialog)
        self.lblPoster.setGeometry(QtCore.QRect(20, 240, 431, 401))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblPoster.setFont(font)
        self.lblPoster.setText("")
        self.lblPoster.setObjectName("lblPoster")
        self.btnSearch = QtWidgets.QPushButton(Dialog)
        self.btnSearch.setGeometry(QtCore.QRect(650, 90, 171, 81))
        self.btnSearch.setObjectName("btnSearch")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(600, 210, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 710, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lblTitle = QtWidgets.QLabel(Dialog)
        self.lblTitle.setGeometry(QtCore.QRect(20, 150, 581, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setWordWrap(True)
        self.lblTitle.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.lblTitle.setObjectName("lblTitle")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(600, 260, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(600, 310, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(600, 360, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lblRelease = QtWidgets.QLabel(Dialog)
        self.lblRelease.setGeometry(QtCore.QRect(800, 210, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblRelease.setFont(font)
        self.lblRelease.setText("")
        self.lblRelease.setObjectName("lblRelease")
        self.lblRuntime = QtWidgets.QLabel(Dialog)
        self.lblRuntime.setGeometry(QtCore.QRect(720, 260, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblRuntime.setFont(font)
        self.lblRuntime.setText("")
        self.lblRuntime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblRuntime.setObjectName("lblRuntime")
        self.lblRated = QtWidgets.QLabel(Dialog)
        self.lblRated.setGeometry(QtCore.QRect(680, 310, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblRated.setFont(font)
        self.lblRated.setText("")
        self.lblRated.setWordWrap(True)
        self.lblRated.setObjectName("lblRated")
        self.Genres = QtWidgets.QLabel(Dialog)
        self.Genres.setGeometry(QtCore.QRect(690, 360, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Genres.setFont(font)
        self.Genres.setText("")
        self.Genres.setObjectName("Genres")
        self.lblPlot = QtWidgets.QLabel(Dialog)
        self.lblPlot.setGeometry(QtCore.QRect(80, 720, 921, 171))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblPlot.setFont(font)
        self.lblPlot.setMouseTracking(True)
        self.lblPlot.setAutoFillBackground(False)
        self.lblPlot.setText("")
        self.lblPlot.setTextFormat(QtCore.Qt.AutoText)
        self.lblPlot.setWordWrap(True)
        self.lblPlot.setObjectName("lblPlot")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Search:"))
        self.label_2.setText(_translate("Dialog", "Movie Searcher"))
        self.btnSearch.setText(_translate("Dialog", "Search"))
        self.label_4.setText(_translate("Dialog", "Release Date:"))
        self.label_5.setText(_translate("Dialog", "Plot"))
        self.lblTitle.setText(_translate("Dialog", "Title"))
        self.label_6.setText(_translate("Dialog", "Runtime:"))
        self.label_7.setText(_translate("Dialog", "Rated:"))
        self.label_8.setText(_translate("Dialog", "Genres:"))

