# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MovieForm.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MovieWindow(object):
    def setupUi(self, MovieWindow):
        MovieWindow.setObjectName("MovieWindow")
        MovieWindow.resize(1062, 785)
        self.centralwidget = QtWidgets.QWidget(MovieWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(0, 20, 1041, 81))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setUnderline(True)
        self.lblTitle.setFont(font)
        self.lblTitle.setText("")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 500, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblPlot = QtWidgets.QLabel(self.centralwidget)
        self.lblPlot.setGeometry(QtCore.QRect(10, 560, 1041, 181))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblPlot.setFont(font)
        self.lblPlot.setText("")
        self.lblPlot.setTextFormat(QtCore.Qt.RichText)
        self.lblPlot.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPlot.setWordWrap(True)
        self.lblPlot.setObjectName("lblPlot")
        self.lblPoster = QtWidgets.QLabel(self.centralwidget)
        self.lblPoster.setGeometry(QtCore.QRect(40, 140, 331, 351))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblPoster.setFont(font)
        self.lblPoster.setText("")
        self.lblPoster.setObjectName("lblPoster")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(390, 140, 641, 351))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lblReleased = QtWidgets.QLabel(self.groupBox)
        self.lblReleased.setGeometry(QtCore.QRect(110, 20, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblReleased.setFont(font)
        self.lblReleased.setText("")
        self.lblReleased.setObjectName("lblReleased")
        self.lblGenres = QtWidgets.QLabel(self.groupBox)
        self.lblGenres.setGeometry(QtCore.QRect(90, 70, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblGenres.setFont(font)
        self.lblGenres.setText("")
        self.lblGenres.setObjectName("lblGenres")
        self.lblDirectors = QtWidgets.QLabel(self.groupBox)
        self.lblDirectors.setGeometry(QtCore.QRect(120, 190, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblDirectors.setFont(font)
        self.lblDirectors.setText("")
        self.lblDirectors.setObjectName("lblDirectors")
        self.lblRated = QtWidgets.QLabel(self.groupBox)
        self.lblRated.setGeometry(QtCore.QRect(100, 250, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblRated.setFont(font)
        self.lblRated.setText("")
        self.lblRated.setObjectName("lblRated")
        self.lblRuntime = QtWidgets.QLabel(self.groupBox)
        self.lblRuntime.setGeometry(QtCore.QRect(110, 130, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblRuntime.setFont(font)
        self.lblRuntime.setText("")
        self.lblRuntime.setObjectName("lblRuntime")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 110, 1061, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MovieWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MovieWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuWatchlist = QtWidgets.QMenu(self.menubar)
        self.menuWatchlist.setObjectName("menuWatchlist")
        MovieWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MovieWindow)
        self.statusbar.setObjectName("statusbar")
        MovieWindow.setStatusBar(self.statusbar)
        self.actionSearch = QtWidgets.QAction(MovieWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionExit_Application = QtWidgets.QAction(MovieWindow)
        self.actionExit_Application.setObjectName("actionExit_Application")
        self.actionAdd_to_Watchlist = QtWidgets.QAction(MovieWindow)
        self.actionAdd_to_Watchlist.setObjectName("actionAdd_to_Watchlist")
        self.actionView_WatchList = QtWidgets.QAction(MovieWindow)
        self.actionView_WatchList.setObjectName("actionView_WatchList")
        self.menuFile.addAction(self.actionSearch)
        self.menuFile.addAction(self.actionExit_Application)
        self.menuWatchlist.addAction(self.actionAdd_to_Watchlist)
        self.menuWatchlist.addAction(self.actionView_WatchList)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWatchlist.menuAction())

        self.retranslateUi(MovieWindow)
        QtCore.QMetaObject.connectSlotsByName(MovieWindow)

    def retranslateUi(self, MovieWindow):
        _translate = QtCore.QCoreApplication.translate
        MovieWindow.setWindowTitle(_translate("MovieWindow", "MainWindow"))
        self.label.setText(_translate("MovieWindow", "Plot"))
        self.groupBox.setTitle(_translate("MovieWindow", "Information"))
        self.label_2.setText(_translate("MovieWindow", "Released"))
        self.label_3.setText(_translate("MovieWindow", "Genres"))
        self.label_4.setText(_translate("MovieWindow", "Runtime"))
        self.label_5.setText(_translate("MovieWindow", "Directors"))
        self.label_6.setText(_translate("MovieWindow", "Rated"))
        self.menuFile.setTitle(_translate("MovieWindow", "File"))
        self.menuWatchlist.setTitle(_translate("MovieWindow", "Watchlist"))
        self.actionSearch.setText(_translate("MovieWindow", "Search "))
        self.actionExit_Application.setText(_translate("MovieWindow", "Exit Application"))
        self.actionAdd_to_Watchlist.setText(_translate("MovieWindow", "Add to Watchlist"))
        self.actionView_WatchList.setText(_translate("MovieWindow", "View WatchList"))

